### ISSUE TITLE
Unexpected exception: Exception ticking world & ConcurrentModificationException

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#12]
## 基本資訊

- 玩家 ID： `fntsrswl`
- 發生時間： `2017-05-09 21:54:46`

## 問題描述

伺服器崩潰。

```
21:54:46 [ERROR] Encountered an unexpected exception
net.minecraft.server.v1_11_R1.ReportedException: Exception ticking world
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:809) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:259) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:798) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        ... 4 more
21:54:46 [ERROR]        Cause of unexpected exception was
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.PlayerChunkMap.flush(PlayerChunkMap.java:122) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:259) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:798) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
21:54:46 [ERROR] This crash report has been saved to: /home/bukkit/Minecraft/Normal/Server/./crash-reports/crash-2017-05-09_21.54.46-server.txt
```

**Comment by fntsrlike** [comment]
@david50407 說可能和我上次貼的這個文章有相關性：

https://www.ptt.cc/bbs/Minecraft/M.1494090377.A.EC7.html

**Comment by fntsrlike** [comment]
最近沒有再看到相關 exception，故關閉。若之後有再看到再重啟。
