### ISSUE TITLE
Skinny Providers Warning 紀錄

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#13]
從 Log 裡翻到的，順手丟上來，看有沒有需要改進。

```
6082 2017-05-20 13:46:37 [WARN] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received f
     rom the server was 39,375,515 milliseconds ago.  The last packet sent successfully to the server was 39,375,515 millisecond
     s ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing con
     nection validity before use in your application, increasing the server configured values for client timeouts, or using the
     Connector/J connection property 'autoReconnect=true' to avoid this problem.
6083 2017-05-20 13:46:37 [WARN]  at sun.reflect.GeneratedConstructorAccessor609.newInstance(Unknown Source)
6084 2017-05-20 13:46:37 [WARN]  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.
     java:45)
6085 2017-05-20 13:46:37 [WARN]  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
6086 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
6087 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
6088 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3743)
6089 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2506)
6090 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
6091 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
6092 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
6093 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
6094 2017-05-20 13:46:37 [WARN]  at org.snowtec.mine.skinny.SnowServerProvider.getSkinData(SnowServerProvider.java:26)
6095 2017-05-20 13:46:37 [WARN]  at tw.davy.minecraft.skinny.providers.ProviderManager.getSkin(ProviderManager.java:40)
6096 2017-05-20 13:46:37 [WARN]  at tw.davy.minecraft.skinny.packet.PlayerInfoPacketAdapter.onPacketSending(PlayerInfoPacketAdap
     ter.java:46)
6097 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketL
     istenerList.java:195)
6098 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketLis
     tenerList.java:149)
6099 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:60
     8)
6100 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.
     java:584)
6101 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:30
     9)
6102 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java
     :269)
6103 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:39
     6)
6104 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77)
6105 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java
     :362)
6106 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.j
     ava:330)
6107 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:12
     7)
6108 2017-05-20 13:46:37 [WARN]  at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
6109 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:194)
6110 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.NetworkManager.sendPacket(NetworkManager.java:143)
6111 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.PlayerConnection.sendPacket(PlayerConnection.java:1090)
6112 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:347)
6113 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160)
6114 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147)
6115 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57)
6116 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233)
6117 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140)
6118 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842)
6119 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
6120 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
6121 2017-05-20 13:46:37 [WARN]  at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
6122 2017-05-20 13:46:37 [WARN]  at java.lang.Thread.run(Thread.java:745)
6123 2017-05-20 13:46:37 [WARN] Caused by: java.net.SocketException: 中斷的管線 (Write failed)
6124 2017-05-20 13:46:37 [WARN]  at java.net.SocketOutputStream.socketWrite0(Native Method)
6125 2017-05-20 13:46:37 [WARN]  at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
6126 2017-05-20 13:46:37 [WARN]  at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
6127 2017-05-20 13:46:37 [WARN]  at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
6128 2017-05-20 13:46:37 [WARN]  at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
6129 2017-05-20 13:46:37 [WARN]  at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3725)
6130 2017-05-20 13:46:37 [WARN]  ... 34 more
6131 2017-05-20 13:46:38 [WARN] [SkinnySnowServer] Connection to MySQL server closed. Reconnecting...

**Comment by davy-tw** [comment]
感覺需要 reconnect to db

**Comment by fntsrlike** [comment]
這個問題是不是已經被修正了？ @david50407

**Comment by davy-tw** [comment]
理論上是
