### ISSUE TITLE
HopperHopper 的 Error 紀錄

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#14]
從 Log 裡翻到的，順手丟上來，看有沒有需要改進。

#### 2017-05-20 01:38:17
```
5807 2017-05-20 01:38:17 [ERROR] Could not pass event EntityDamageByEntityEvent to HopperHopper v1.0-SNAPSHOT
5808 org.bukkit.event.EventException
5809     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5810     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5811     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5812     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5813     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:90) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5814     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:575) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5815     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:480) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5816     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:626) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5817     at net.minecraft.server.v1_11_R1.EntityItemFrame.damageEntity(EntityItemFrame.java:39) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5818     at net.minecraft.server.v1_11_R1.EntityHanging.t(EntityHanging.java:164) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5819     at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:955) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5820     at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1145) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5821     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5822     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5823     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5824     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5825     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
5826     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
5827     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5828     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5829     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5830     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5831     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5832     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
5833 Caused by: java.lang.NullPointerException
5834     at tw.davy.minecraft.hopperhopper.database.SqliteDatabase.clearFilter(SqliteDatabase.java:132) ~[?:?]
5835     at tw.davy.minecraft.hopperhopper.database.MetadataDatabase.clearFilter(MetadataDatabase.java:51) ~[?:?]
5836     at tw.davy.minecraft.hopperhopper.listener.ItemFrameEventListener.onItemFrameItemRemove(ItemFrameEventListener.java:90) ~[?:?]
5837     at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
5838     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
5839     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
5840     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5841     ... 23 more
```

#### 2017-05-20 02:03:38

```
5936 2017-05-20 02:03:38 [ERROR] Could not pass event EntityDamageByEntityEvent to HopperHopper v1.0-SNAPSHOT
5937 org.bukkit.event.EventException
5938     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5939     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5940     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5941     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5942     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:90) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5943     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:575) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5944     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:480) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5945     at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:626) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5946     at net.minecraft.server.v1_11_R1.EntityItemFrame.damageEntity(EntityItemFrame.java:39) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5947     at net.minecraft.server.v1_11_R1.EntityHanging.t(EntityHanging.java:164) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5948     at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:955) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5949     at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1145) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5950     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1568) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5951     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5952     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5953     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5954     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
5955     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
5956     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5957     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5958     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5959     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5960     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5961     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
5962 Caused by: java.lang.NullPointerException
5963     at tw.davy.minecraft.hopperhopper.database.SqliteDatabase.clearFilter(SqliteDatabase.java:132) ~[?:?]
5964     at tw.davy.minecraft.hopperhopper.database.MetadataDatabase.clearFilter(MetadataDatabase.java:51) ~[?:?]
5965     at tw.davy.minecraft.hopperhopper.listener.ItemFrameEventListener.onItemFrameItemRemove(ItemFrameEventListener.java:90) ~[?:?]
5966     at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[?:?]
5967     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
5968     at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
5969     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
5970     ... 23 more
```

**Comment by fntsrlike** [comment]
2017-05-19 04:39:51 ~ 2017-05-20 01:15:21 之間也陸續有 Error

**Comment by davy-tw** [comment]
fixed at https://github.com/david50407/HopperHopper/commit/31141bacc25835ab79fa6d266b0630d7ec06028c

是說這種 issue 我覺得開在對應專案好一點 @fntsrlike

**Comment by fntsrlike** [comment]
Ok ok
