### ISSUE TITLE
TC 錯誤造成無法登入

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#31]
## 基本資訊

- 玩家 ID： `Ureezu -`
- 發生時間： `2017-08-12 08:05`

## 問題描述
達人在 discord 表示無法登入
![2017-08-12 10 16 52](https://user-images.githubusercontent.com/2680724/29236995-638c493a-7f47-11e7-8ce6-5e3249d79514.png)

![2017-08-12_8 04 00](https://user-images.githubusercontent.com/2680724/29236929-0e6cdeca-7f46-11e7-8b96-7be658c55c0b.png)

## 處理過程
2017-08-12 03:39 發出警報
![2017-08-12 10 10 21](https://user-images.githubusercontent.com/2680724/29236980-273b6272-7f47-11e7-91f3-9eef512f5e76.png)

```
2017-08-12 03:39:45 [ERROR] [Train_Carts] An error occurred in RailType 'RailTypeVertical'
java.lang.OutOfMemoryError: Java heap space
	at java.util.IdentityHashMap.resize(IdentityHashMap.java:471) ~[?:1.8.0_131]
	at java.util.IdentityHashMap.put(IdentityHashMap.java:440) ~[?:1.8.0_131]
	at com.bergerkiller.bukkit.common.wrappers.BlockDataRegistry.fromBlockData(BlockDataRegistry.java:45) ~[BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.common.utils.WorldUtil.getBlockData(WorldUtil.java:87) ~[BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.tc.rails.type.RailType.isRail(RailType.java:147) ~[TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.rails.type.RailType.isRail(RailType.java:169) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.rails.type.RailType.getType(RailType.java:113) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.onBlockCollision(MinecartMember.java:793) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.world_getBlockCollisions(EntityMoveHandler.java:147) [BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.world_getCubes(EntityMoveHandler.java:160) [BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.move(EntityMoveHandler.java:355) [BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.common.controller.EntityController.onMove(EntityController.java:148) [BKCommonLib.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:1099) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberHopper.onPhysicsPostMove(MinecartMemberHopper.java:27) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1022) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:928) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1189) [TrainCarts.jar:?]
	at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:113) [BKCommonLib.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen72b95eb3.invokeVA(Unknown Source) [?:?]
	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:627) [BKCommonLib.jar:?]
	at net.minecraft.server.v1_12_R1.EntityMinecartHopper$$EnhancerByCGLIB$$773434f0.B_(<generated>) [BKCommonLib.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1639) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1609) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-99c2a37-d35483b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

詳細 Log 可參見：
https://gist.github.com/fntsrlike/34dd7cfb252042b406f296455e77a751

**Comment by davy-tw** [comment]
應該不是tc造成的 只是剛好記憶體沒了？

**Comment by fntsrlike** [comment]
是，雪人有說
> 我知道為什麼了，有開 profiler 這個 shell script 只有給他 5G 的記憶體

所以是記憶體的問題沒錯，可以先關這議題了。
